services:
  payments-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudgames-Payment
    ports:
      - "5058:5058"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:5058"

      Jwt__Key: "chave-secreta-super-forte-123456"
      Jwt__Issuer: "CloudGamesAPI"
      Jwt__Audience: "CloudGamesAPIClient"

      RabbitMq__HostName: "cloudgames-rabbitmq" 
      RabbitMq__Port: "5672"
      RabbitMq__UserName: "guest"
      RabbitMq__Password: "guest"
      RabbitMq__ExchangeName: "cloudgames.topic"
      RabbitMq__QueueNameOrderPlaced: "OrderPlacedEvent"
      RabbitMq__QueueNamePaymentProcessed: "PaymentProcessedEvent"

    networks:
      - cloudgames-network

networks:
  cloudgames-network:    
    external: true