services:
  payments-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudgames-Payment
    ports:
      - "5058:5058"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:5058"

      Jwt__Key: "chave-secreta-super-forte-123456"
      Jwt__Issuer: "CloudGamesAPI"
      Jwt__Audience: "CloudGamesAPIClient"

      ServiceBus__ConnectionString: ""
      ServiceBus__QueueNameOrderPlaced: "OrderPlacedEvent"
      ServiceBus__QueueNamePaymentProcessed: "PaymentProcessedEvent"
      APPLICATIONINSIGHTS_CONNECTION_STRING: ""

    networks:
      - cloudgames-network

networks:
  cloudgames-network:
    external: true
