apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
  labels:
    app: payments-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_HTTP_PORTS: "5058"
  RabbitMq__HostName: "cloudgames-rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__ExchangeName: "cloudgames.topic"
  RabbitMq__QueueNameOrderPlaced: "OrderPlacedEvent"
  RabbitMq__QueueNamePaymentProcessed: "PaymentProcessedEvent"
