apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
  labels:
    app: payments-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_HTTP_PORTS: "5058"
  Jwt__Issuer: "CloudGamesAPI"
  Jwt__Audience: "CloudGamesAPIClient"
  ServiceBus__OrderPlacedTopicName: "order-placed"
  ServiceBus__OrderPlacedSubscriptionName: "payments-api"
  ServiceBus__PaymentProcessedTopicName: "payment-processed"
