apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secret
  labels:
    app: payments-api
type: Opaque
stringData:
  Jwt__Key: "chave-secreta-super-forte-123456"
  ServiceBus__ConnectionString: ""
  APPLICATIONINSIGHTS_CONNECTION_STRING: ""
