apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secret
  labels:
    app: payments-api
type: Opaque
data:
  # Base64 encoded values
  # JWT Key for authentication
  Jwt__Key: Y2hhdmUtc2VjcmV0YS1zdXBlci1mb3J0ZS0xMjM0NTY=
  # RabbitMQ credentials (guest/guest)
  RabbitMq__UserName: Z3Vlc3Q=
  RabbitMq__Password: Z3Vlc3Q=
